name: Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Determine Version
        run: echo "VERSION=0.1.0-alpha.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build for Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o geomys-${{ env.VERSION }}-linux-amd64 ./cmd/server/main.go

      - name: Build for Windows (amd64)
        run: |
          GOOS=windows GOARCH=amd64 go build -o geomys-${{ env.VERSION }}-windows-amd64.exe ./cmd/server/main.go

      - name: Build for Linux (client) (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o geomys-client-${{ env.VERSION }}-linux-amd64 ./cmd/client/main.go

      - name: Build for Windows (Client) (amd64)
        run: |
          GOOS=windows GOARCH=amd64 go build -o geomys-client-${{ env.VERSION }}-windows-amd64.exe ./cmd/client/main.go

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Geomys ${{ env.VERSION }}
          draft: false
          prerelease: true
          files: |
            geomys-${{ env.VERSION }}-linux-amd64
            geomys-${{ env.VERSION }}-windows-amd64.exe
            geomys-client-${{ env.VERSION }}-linux-amd64
            geomys-client-${{ env.VERSION }}-windows-amd64.exe
