name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Run Unit Tests
        run: go test ./tests/unit/... -v
      - name: Run Integration Tests
        run: go test ./tests/integration/... -v
